global:
  scrape_interval: 1s # How frequently to scrape targets

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"] # Prometheus itself

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"] # Node Exporter service

  - job_name: "example_app"
    static_configs:
      - targets: ["example_app:8080"]
